---
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
