# This is a basic workflow to help you get started with Actions

name: lint-check

on: 
 push :
  branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run eslint
        run: make lint
