name: eslint checker

on:
  - push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Linter
      - run: make install
      - run: make lint


